domain_not_exist_patterns = [
    r'domain not found',
    r'no such host is known.',
    r'no match for',
    r'No whois information found\.',
    r'No Data Found',
    r'nothing found',
    r'No entries found',
    r'ERROR:101: no entries found',
    r'No data was found to match the request criteria\.',
    r'Domain Status: No Object Found',
    r'The requested domain was not found',
    r'query_status: 220 Available',
    r'Domain not found',
    r'NOT FOUND',
    r'No Object Found',
    r'Not found: [\w\d\-\.]+',
    r'No information available about domain name',
    r'The queried object does not exist',
    r'does not exist in database',
    r'no existe',
    r'Status: free',
    r'No Match',
    r'[\w\d\-\.]+ is free',
    r'domain name not known',
    r'Status:\s*AVAILABLE',
    r'Domain [\w\d\-\.]+ is available for purchase',
    r'this server does not have .* any data for [\w\d\-\.]+',
    r'Object_Not_Found',
    r'The domain has not been registered',
    r'Status: Not Registered',
    r'-7: %Invalid pattern',
    r'We do not have an entry in our database matching your query',
    r'No Found',
    r'%ERROR:103: Domain is not registered',
    r'% Not Registered',
    r'name or service not known',
]
